### ISSUE TITLE
Some `tf.Operation.inputs` need to be remapped to match the OpDef signature

### ISSUE THREAD

**Issue by josephwillard** [pymc-devs/symbolic-pymc#28] opened 2019-06-09 03:27 UTC
The following code produces an error,

```python
import tensorflow as tf
from tensorflow.python.framework.ops import disable_eager_execution

from symbolic_pymc.unify import tuple_expression

disable_eager_execution()

t1 = [[1, 2, 3], [4, 5, 6]]
t2 = [[7, 8, 9], [10, 11, 12]]
z = tf.concat([t1, t2], 0)

tuple_expression(z)
```
the expected output should be along the lines of `etuple(tf.ConcatV2, t1, t2, 0)`.

**Comment by brandonwillard** [comment] 2019-06-13 02:53
The problem occurs in [`TFlowMetaOpDef`](https://github.com/pymc-devs/symbolic-pymc/blob/master/symbolic_pymc/tensorflow/meta.py#L228) where it attempts to craft a set of arguments in accordance with the underlying `OpDef`'s inputs.  We're effectively using `tf.Operation.inputs` to get some of those values, but it uses the underlying C api and that happens to flatten some inputs that the `OpDef` knows as lists/arrays.  

Specifically, the `OpDef` for `ConcatV2` expects `values` and `axis` arguments/inputs, but `tf.Operation.inputs` returns `values + [axis]`, which&mdash;in our example&mdash;results in `[t1, t2, 0]`.  That causes errors when we apply the `Signature` assigned to the meta `TFlowMetaOpDef` (which follows the underlying `OpDef` and requires a single `values` list and `axis`), because there are too many arguments.

The answer lies in [`tf.Operation._reconstruct_sequence_inputs`](https://github.com/tensorflow/tensorflow/blob/0dfa20a5603c1293e495de372e6fcfeb43feeb98/tensorflow/python/framework/ops.py#L1743), where the output of `tf.Operation.inputs` is reassembled into the correct form for the corresponding `OpDef`.  We need to reproduce the steps in that function, but that may also involve tracking more `tf.Operation.node_def.attr` information [than we currently are](https://github.com/pymc-devs/symbolic-pymc/blob/master/symbolic_pymc/tensorflow/meta.py#L320) (i.e. whatever `tf.Operation._reconstruct_sequence_inputs` is using from `tf.Operation.node_def`).

It seems like the aforementioned change is best placed in a new method called `TFlowMetaOp.inputs`, so that it intercepts our current use of the same-named method that is currently being dispatched to the underlying TF object in `TFlowMetaOp.obj`.  That also puts the implementation in a position to use the requisite `NodeDef` information in `TFlowMetaOp.node_def`.

**Closed** 2019-07-02 03:00 UTC
Labels: bug, important
